### ISSUE TITLE
Jasmine Testing - 404 angular2-logger/core.js

### ISSUE THREAD

**Issue by vijayaragavendiran** [code-chunks/angular2-logger#32]
Hi,
I am using angular2-logger in my component, I wrote a spec for component and executed the test.  But I am getting below error.
02 05 2016 17:17:36.691:WARN [web-server]: 404: /base/angular2-logger/core.js
Chrome 50.0.2661 (Windows 7 0.0.0) ERROR: Error{originalErr: Error{}}
02 05 2016 17:17:37.448:WARN [web-server]: 404: /base/angular2-logger/core.js.

Please guide me.

Thanks,
Vj

**Comment by langley-agm** [comment]
Hello @vijayaragavendiran ,

The issue you are having is because you are trying to load the logger library from a folder called base and you don't have the library there. The library should be in a node_modules folder if you are following the quickstart instructions.

Can you show me the content of the file that throws you this error and your project's files structure so I can help you troubleshoot the issue?

Even easier to spot if you can replicate your issue in [plunkr ](https://plnkr.co/) or similar.

**Comment by langley-agm** [comment]
Closing it for now, will reopen if the issue continues and more info is provided in order to help fix it.
