### ISSUE TITLE
Using store() is not working as expected

### ISSUE THREAD

**Issue by nilseckert** [code-chunks/angular2-logger#80]
I tried to use store() to persist the dynamically changed logger settings.

My test was 

```
logger.level = logger.Level.DEBUG;
logger.store();
```

The value is stored in localStorage as `4`.

Before refreshing the browser `isInfoEnabled()` and `isDebugEnabled()` are working as expected. But after refreshing the browser internal state`level` is now a `string` value: `DEBUG`.

I created a fork and removed the cast to `string` in the following line (logger.ts):

```
private _loadLevel = (): Level => Level[localStorage.getItem( this._storeAs ) as string];
```

This solved the issue for me. I will provide a pull request for that.

**Comment by langley-agm** [comment]
@nilseckert casting is a compiler time feature not runtime, it shouldn't change the functionality once its converted to JS. I tried to reproduce your error but I get ´4´ after refreshing not `DEBUG` do you have a project or snipet to reproduce your issue?

**Comment by langley-agm** [comment]
Hi @nilseckert nice finding.

However I don't think `as string` is the issue, casting is a compile time/typescript only feature, it shouldn't affect the runtime/js functionality. 

The issue is caused by the `Level[]` notation. Typescript brings back either the key if you look for the value, or the value if you look for the key. That's because they translate the enum to an array similar to this:

	0: "OFF"
	1: "ERROR"
	...
	DEBUG: 4
	ERROR: 1
	...

I tried the solution in your pull request and it didn't fix it for me. Do you mind double checking? else if you apply the changes in the comments I added, I'll apply your pull request, thanks for your contribution =)
